### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by alluding** [Xewdy444/Playwright-reCAPTCHA#107]
No clue if this is possible. I mean, it was logical enough to work with a Cloudflare turnstile solver. Couldn't you use the reCaptcha challenge URI (given by a user) and build a separate page (local) with just the captcha? As of now, this is limited to pages where the captcha is visible without needing to do other actions. What I'm suggesting would, I mean, logically erase this limitation, as you could solve the captcha without requiring the other actions.

**Comment by Xewdy444** [comment]
You can do something like this:
```py
from playwright.sync_api import sync_playwright

from playwright_recaptcha import recaptchav2

RECAPTCHA_HTML = """
<!DOCTYPE html>
<html>
    <head>
        <script src="https://www.google.com/recaptcha/api.js" async
            defer></script>
    </head>
    <body>
        <div
            class="g-recaptcha"
            data-sitekey="{sitekey}"></div>
    </body>
</html>
"""


def main() -> None:
    with sync_playwright() as playwright:
        browser = playwright.firefox.launch()
        page = browser.new_page()
        page.goto("https://www.google.com")

        page.set_content(
            RECAPTCHA_HTML.format(sitekey="6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-")
        )

        with recaptchav2.SyncSolver(page) as solver:
            token = solver.solve_recaptcha(wait=True)
            print(token)


if __name__ == "__main__":
    main()
```
The one requirement is that you load a website with the page before setting the reCAPTCHA HTML. If you don't, you'll get this error:
![image](https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/95155966/3580d4f4-a86b-4bce-8249-27c642faa813)

**Comment by Xewdy444** [comment]
Added an [example for this](https://github.com/Xewdy444/Playwright-reCAPTCHA/commit/7680dd6fc25f761237654830079ffb467423e284)
