### ISSUE TITLE
Hcaptcha?

### ISSUE THREAD

**Issue by rastarr** [Xewdy444/Playwright-reCAPTCHA#19]
Are you looking to incorporate solving HCaptcha at any time?

**Comment by Xewdy444** [comment]
I do not plan on incorporating hCaptcha solving as this library is specifically for reCAPTCHA. For hCaptcha, I would recommend using the hektCaptcha browser extension: https://github.com/Wikidepia/hektCaptcha-extension. This extension can be used with Playwright to solve hCaptchas automatically.
