### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by rastarr** [Xewdy444/Playwright-reCAPTCHA#2]
I'm just a newbie but looking to use this with GSA CaptchaBreaker in some way.
How do I even test this with a URL?
Can you help with examples of how to run? Ideally, I'd like to run this inside a Docker container and send requests to it via GSA CB

Any help would be fantastic

**Comment by Xewdy444** [comment]
I'm not familiar with the software you mentioned, however, playwright-recaptcha could be implemented into an API using something such as Flask or FastAPI which could accept the solve requests, solve the reCAPTCHA, and return the response token. I have listed usage examples in the README. There are also some examples in the examples folder for each reCAPTCHA type.

**Comment by rastarr** [comment]
@Xewdy444 Thanks so much for the reply.
Sadly, I'm not a coder so no chance I could do this. Hopefully, someone else in the same situation can make good use of your advice.
