### ISSUE TITLE
Make checkbox optional

### ISSUE THREAD

**Issue by neugartf** [Xewdy444/Playwright-reCAPTCHA#30]
Hey! Thanks for providing this solution :) Really nicely designed.

I happen to run into a scenario where there is no checkbox with "I'm not a robot", but the recaptcha gets invoked on a button click (I assume).

```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("checkbox", name="I'm not a robot")
```

Would that make sense to make this click event optional?

This is the moment it runs into  the timeout:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/6741676/229182374-a8f80cdf-7317-4626-932b-8123b2e334a7.png">

**Comment by Xewdy444** [comment]
Alright, I have made some changes that should allow you to solve reCAPTCHA v2 hidden. To install the updated version, run `pip install git+https://github.com/Xewdy444/Playwright-reCAPTCHA.git@reCAPTCHA-v2-hidden-support`.
Then, let me know if this has solved your issue.

**Comment by Xewdy444** [comment]
I have merged the changes that added support for reCAPTCHA v2 hidden, so simply update playwright-recaptcha using the following command: `pip install -U playwright-recaptcha`
