### ISSUE TITLE
No such file or directory: 'ffprobe'

### ISSUE THREAD

**Issue by DavidIsrayelyan** [Xewdy444/Playwright-reCAPTCHA#38]
Hello. 

I am trying to run the code, for passing recaptcha v2. 
But I am receiving this kind of error. 
I have ffmpeg and ffprobe files near, and I have already installed ffmpeg using brew, but anyway I got this error message. 
Can you help me to solve this problem? 

Thank you. 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/22592990/235879005-b63c1f5a-cc7f-4e06-a229-d038f4f80c0d.png">

**Comment by DavidIsrayelyan** [comment]
@Xewdy444 Anyway I have a problem. I could temporary solve this, but it failed again.

**Comment by DavidIsrayelyan** [comment]
@Xewdy444 I have already installed it using brew and ffmpeg and ffprobe both are in PATH. 
But I have found a solution using these steps. 

import os 
os.environ["PATH"] += os.pathsep + '/opt/homebrew/bin'

With these changes, it worked well, but I have no idea how long will it work.
Maybe, do you know better way to fix this?

**Comment by DavidIsrayelyan** [comment]
I have installed it using brew, and typing in cmd which ffprobe it shows '/opt/homebrew/bin/ffprobe'

**Comment by Xewdy444** [comment]
Then it should work after adding `/opt/homebrew/bin/` to your system's PATH.

**Comment by DavidIsrayelyan** [comment]
Do you mean $PATH ? 
If yes, this directory already is in my PATH.
