### ISSUE TITLE
Recaptcha rate limit and headless issue

### ISSUE THREAD

**Issue by choff5507** [Xewdy444/Playwright-reCAPTCHA#48]
Trying this out and have a couple issues Im hoping I can get assistance with. 

In headless mode it never seems to work, I get an error that that recaptcha limit has been exceeded. It will generally work in headed mode however. I am using the chromium browser and this does not seem to be an issue when using this with FireFox. Also, this is on a site OTHER than the demo google site. 

any advice?

Thanks!

**Comment by Xewdy444** [comment]
Google is most likely detecting headless chromium as being automated. When Google detects requests that are most likely coming from an automated source (either by an automated browser or script), then they will display an error message. An easy workaround for this is using Firefox as you mentioned. You could also try using the playwright-stealth library, although I cannot confirm this will help.

**Comment by mx009gt** [comment]
Not working ((

**Comment by mx009gt** [comment]
playwright_recaptcha.errors.RecaptchaTimeoutError: The reCAPTCHA solve timeout has been exceeded.

**Comment by Xewdy444** [comment]
> playwright_recaptcha.errors.RecaptchaTimeoutError: The reCAPTCHA solve timeout has been exceeded.

Hello, could you please open a separate issue
