### ISSUE TITLE
Request timed out after 

### ISSUE THREAD

**Issue by YonQua** [Xewdy444/Playwright-reCAPTCHA#49]
=========================== logs ===========================
→ POST https://api.capsolver.com/createTask
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
  accept: */*
  accept-encoding: gzip,deflate,br
  content-type: application/json
  content-length: 52577
============================================================

**Comment by Xewdy444** [comment]
This appears to be a network-related issue.
