### ISSUE TITLE
Is this library firefox browser only, and not compatible with webkit and chromium browsers? I tried both of them and they failed to work.

### ISSUE THREAD

**Issue by YonQua** [Xewdy444/Playwright-reCAPTCHA#50]
Is this library firefox browser only, and not compatible with webkit and chromium browsers? I tried both of them and they failed to work.

**Comment by Xewdy444** [comment]
Works for all browsers.

**Comment by YonQua** [comment]
from playright.sync_api import sync_playwright
from playwright_recaptcha import recaptchav2


with sync_playwright() as playwright:
    browser = playwright.firefox.launch()
    page = browser.new_page()
    page.goto("https://www.google.com/recaptcha/api2/demo")

    with recaptchav2.SyncSolver(page) as solver:
        token = solver.solve_recaptcha(wait=True)
        print(token)
        
     I tested with your example, I just changed the default firefox to webkit and chromium, and they didn’t work. I also used await self.page.pause() to follow up, and it kept looping until it timed out.

**Comment by Xewdy444** [comment]
Can you please explain what you mean when you say they didn't work.

**Comment by YonQua** [comment]
<img width="1126" alt="image" src="https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/18325417/851c1c08-9cb3-4f06-886b-f58c8fdf8e2b">
<img width="1349" alt="image" src="https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/18325417/cc28bb4a-9a63-4694-9442-e6f8112cf92a">

**Comment by YonQua** [comment]
<img width="1350" alt="image" src="https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/18325417/ae1314ba-284f-4ab6-9f28-2064afbd7793">

**Comment by Xewdy444** [comment]
English is the only supported language currently.
