### ISSUE TITLE
 I made a mistake somewhere...

### ISSUE THREAD

**Issue by mx009gt** [Xewdy444/Playwright-reCAPTCHA#59]
I can't solve the captcha. The page at the URL opens, but nothing happens ((

`
from playwright.sync_api import sync_playwright
from playwright_recaptcha import recaptchav3
import time
#import re

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(headless=False)
    page = browser.new_page()
    page.goto("https://visa.vfsglobal.com/us/en/fra/login")
    time.sleep(10) 

    with recaptchav3.SyncSolver(page) as solver:
        page.frame_locator('iframe[title="reCAPTCHA"]').get_by_role("checkbox").click()
        token = solver.solve_recaptcha()
        print(token)
        page.evaluate('document.getElementById("g-recaptcha-response").innerHTML="token";', token)

`

**Comment by Xewdy444** [comment]
The https://visa.vfsglobal.com/us/en/fra/login page has a reCAPTCHA v2, so you should use the `recaptchav2.SyncSolver()` instead.

**Comment by kashcode** [comment]
I have question how to know what type of captcha is used by site?

**Comment by Xewdy444** [comment]
> I have question how to know what type of captcha is used by site?

Check out this blog post: https://www.capsolver.com/blog/reCAPTCHA/identify-what-recaptcha-version-is-being-used
