### ISSUE TITLE
waiting for get_by_role("checkbox", name="I'm not a robot")

### ISSUE THREAD

**Issue by rastarr** [Xewdy444/Playwright-reCAPTCHA#6]
testing recaptcha v2 and getting 'waiting for get_by_role("checkbox", name="I'm not a robot")' errors
Is there a solution for this available?

**Comment by Xewdy444** [comment]
Test this branch to see if this has fixed the issue:

```
pip install git+https://github.com/Xewdy444/Playwright-reCAPTCHA.git@6-waiting-for-get_by_rolecheckbox-name=im-not-a-robot
```

**Comment by rastarr** [comment]
Well, unsure if it is working actually
Got the same error when testing against https://votreassistantprive.fr/forum/login

**Comment by Xewdy444** [comment]
It looks like this website is using reCAPTCHA v2 invisible for the "Learn More" > "Contact Us" form. In order to use this solver with this page, you must first fill out the information on the form and click the "Send" button in order for the reCAPTCHA to show. Then, you can call the `solve_recaptcha()` method to solve this reCAPTCHA.

**Comment by rastarr** [comment]
@Xewdy444 OK thank you so much for that.
BTW can I pass a proxy IP in some way to be used by the solver?

**Comment by Xewdy444** [comment]
Yes, you can pass a proxy to be used by the browser like this:

## With Authentication
```py
browser = playwright.chromium.launch(
    {
        "server": "http://1.1.1.1:3128",
        "username": "username",
        "password": "password",
    }
)
```

## Without Authentication
```py
browser = playwright.chromium.launch({"server": "http://1.1.1.1:3128"})
```

**Comment by rastarr** [comment]
@Xewdy444 TypeError: launch() takes 1 positional argument but 2 were given

**Comment by Xewdy444** [comment]
Sorry about that. I initially forgot to include proxy= in my example.
