### ISSUE TITLE
How to specific page-action?

### ISSUE THREAD

**Issue by otrumb** [Xewdy444/Playwright-reCAPTCHA#73]
Is there any way to specific page-action?

**Comment by Xewdy444** [comment]
Could you please clarify as to what you mean.

**Comment by otrumb** [comment]
Hi @Xewdy444 ,

Some website owner defines what user is doing on the page through action parameter.
Example: `grecaptcha.execute('site_key', {action:'login_test'})`

![image](https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/138744580/30ae8951-893b-44e1-9ca4-39bc4ca5e24e)

So, there are any ways to specific this parameter? Like other captcha solver service do (ex: 2captcha as image below)
![image](https://github.com/Xewdy444/Playwright-reCAPTCHA/assets/138744580/a4e32b66-f905-4482-a396-f080206e2590)

**Comment by Xewdy444** [comment]
You could possibly edit this in the page itself by running some JavaScript with the `evaluate()` method of `playwright.sync_api.Locator` or `playwright.async_api.Locator`.
