### ISSUE TITLE
Can slow v2 down? how?

### ISSUE THREAD

**Issue by rastarr** [Xewdy444/Playwright-reCAPTCHA#8]
"An exception raised when the reCAPTCHA rate limit has been reached. This can happen if the library is being used to solve reCAPTCHA v2 too quickly."

This seems to happen more often than not in my newbie testing.
Is there some way to slow things down to get the solver to work?
This even happens for me using https://www.google.com/recaptcha/api2/demo as the target

**Comment by Xewdy444** [comment]
You could try sleeping in between each solve or using a proxy with the browser.
