### ISSUE TITLE
How to work through a proxy?

### ISSUE THREAD

**Issue by Roboxkin** [Xewdy444/Playwright-reCAPTCHA#88]
I think that after several requests Google will block the IP, is there a way to make requests for a solution through a proxy? To avoid being blacklisted
Any ideas?
Thank you

**Comment by Xewdy444** [comment]
When you create the Playwright browser, you can specify a proxy server to use. Here is an example:
```py
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(
        proxy={
            "server": "http://localhost:8080",
            "username": "username",  # Optional
            "password": "password",  # Optional
        }
    )
```

**Comment by Roboxkin** [comment]
Thank you very much for the answer!
This is a great solution!
Have a good day
