### ISSUE TITLE
Doesn't work on Chrome

### ISSUE THREAD

**Issue by LipeTadeu** [Xewdy444/Playwright-reCAPTCHA#91]
Hi, how are you?
Do you know why it doesn't run in Chrome when we use headless=False?

example:

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)

He opens the browser but does not resolve recaptcha and does not even click on recaptcha.

That doesn't work either.

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel='chrome',headless=False)

only works in Firefox.

Thank.

**Comment by Xewdy444** [comment]
What version of Playwright are you using? I tried an example with Chromium and it solved it with no issues:
```py
from playwright.sync_api import sync_playwright
from playwright_recaptcha import recaptchav2

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://www.google.com/recaptcha/api2/demo")

    with recaptchav2.SyncSolver(page) as solver:
        token = solver.solve_recaptcha(wait=True)
        print(token)
```

**Comment by LipeTadeu** [comment]
Hello!
All is well?

Here it doesn't really run using Chrome, it only runs if headless=True.

I'm using version playwright==1.33.0

Which one do you run on your machine?

**Comment by Xewdy444** [comment]
Try updating Playwright to the latest version with the command: `pip install -U playwright` and see if this fixes the issue.

**Comment by Xewdy444** [comment]
Glad to see that you fixed the issue. This library currently supports English and Russian reCAPTCHA, however I could add support for your language as well if you don't mind telling me what it is.

**Comment by LipeTadeu** [comment]
Hello!
Wow, that's great, I don't mind.
I'm Brazilian, Brazilian Portuguese.
I would appreciate it if you could give me your email, I would like to make you a development proposal.

**Comment by Xewdy444** [comment]
Yea sure, my contact information is on [my GitHub profile](https://github.com/Xewdy444).
