### ISSUE TITLE
Warning for non-available translations for Recaptchav2

### ISSUE THREAD

**Issue by Tagge** [Xewdy444/Playwright-reCAPTCHA#97]
Hi,

First and foremost, thanks for making this plugin for Playwright, this really makes the job of implementing Capsolver much easier. It is appreciated !

However, I think it would be worth mentioning in the README that if your Recaptcha is in a locale that is not available in the translations.py file, the plugin won't be able to find any of the elements it needs to interact with the captcha. I had to discover this the hard way while trying to use it on a French website. I have added the translations for this language, and will probably make a PR sometimes to add it to the repo.

Let me know your thoughts about this !

**Comment by Xewdy444** [comment]
It was actually in my todo list to add a list of supported languages to the README, so I apologize for that. I will be adding more translations soon and I will get that done at the same time. The pull request for french support would also be much appreciated.

**Comment by Xewdy444** [comment]
Added in [latest release](https://github.com/Xewdy444/Playwright-reCAPTCHA/releases/tag/v0.5.1)
